spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking?useSSL=false&useUnicode=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  application:
    name: booking
  profiles:
    active: ${ACTIVE_PROFILE:dev}
    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 15MB

jwt:
  header: Authorization
  secret: EqumLAvSIA8T1SWyrnpT

paging:
  default:
    page: 0
    size: 20

file:
  upload_dir: "./uploads"
  download_dir: "./downloads"

google:
  verifyUrl: https://www.googleapis.com/oauth2/v3/tokeninfo?access_token=

server:
  port: 8080
  error:
    include-message: always
